#SPDX-License-Identifier: MIT-0
---
# folder structure for roles/home_configuration

# Check and Define Gnome Profile ID
- name: Get Gnome Profile ID List
  ansible.builtin.command: |
    gsettings get org.gnome.Terminal.Legacy.ProfilesList default
  become: false
  register: default_profile

- name: Set Profile ID
  ansible.builtin.set_fact:
    profile_id: "{{ default_profile.stdout[1:-1] }}"
  when: dconf_profiles.stdout != ""

- name: Debug
  ansible.builtin.debug:
    msg: "{{ profile_id }}"

- name: Set Default Profile ID when Previous Taks Failed
  ansible.builtin.set_fact:
    profile_id: ":{{ ansible_date_time.iso8601_micro | to_uuid }}/"
  when: dconf_profiles.stdout == ""
  become: true
  become_method: sudo

- name: Set Profile Name
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" visible-name {{ user }}
  become: true
  become_method: sudo

- name: Turn Audible Bell Off
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" audible-bell false
  become: true
  become_method: sudo

- name: Set Background Colour
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" background-color 'rgb(0,0,0)'
  become: true
  become_method: sudo

- name: Set Background Transparency Option
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" background-transparency-percent 50
  become: true
  become_method: sudo

# - name: Set Transparencey Theme to false
#   ansible.builtin.command:
#     key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}use-theme-transparency
#     value: "false"
#   become: true
#   become_method: sudo

# - name: Define Background Transparency Value
#   community.general.dconf:
#     key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}background-transparency-percent
#     value: "50"
#   become: true
#   become_method: sudo

- name: Disable Menu Bar
  community.general.dconf:
    key: /org/gnome/terminal/legacy/:headerbar
    value: "false"
  become: true
  become_method: sudo

- name: Set Scrollback to Value unlimited
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" scrollback-unlimited true
  become: true
  become_method: sudo

- name: Set Terminal Default Width
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" default-size-columns 150
  become: true
  become_method: sudo

- name: Set Terminal Default Height
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" default-size-rows 80
  become: true
  become_method: sudo

- name: Set Terminal Encoding
  ansible.builtin.command: |
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/{{ profile_id }}" encoding 'UTF-8'
  become: true
  become_method: sudo

# Define TMUX 
# - name: Set custom-command
#   dconf:
#     key: "/org/gnome/terminal/legacy/profiles:/{{profile_id}}custom-command"
#     value: "'tmux'"
#
# - name: Set use-custom-command
#   dconf:
#     key: "/org/gnome/terminal/legacy/profiles:/{{profile_id}}use-custom-command"
#     value: "true"

