#SPDX-License-Identifier: MIT-0
---
# folder structure for roles/home_configuration

# Check and Define Gnome Profile ID
- name: Get Gnome Profile ID List
  ansible.builtin.command: dconf list "/org/gnome/terminal/legacy/profiles:/"
  become: false
  register: dconf_profiles

- name: Set Profile ID
  ansible.builtin.set_fact:
    profile_id: "{{ dconf_profiles.stdout_lines[0] }}"
  when: dconf_profiles.stdout != ""
  become: true
  become_method: sudo

- name: Set Default Profile ID when Previous Taks Failed
  ansible.builtin.set_fact:
    profile_id: ":{{ ansible_date_time.iso8601_micro | to_uuid }}/"
  when: dconf_profiles.stdout == ""
  become: true
  become_method: sudo

- name: Set Profile Name
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}visible-name
    value: "'{{ user }}'"
  become: true
  become_method: sudo

- name: Turn Audible Bell Off
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}audible-bell
    value: "false"
    state: present
  become: true
  become_method: sudo

- name: Set Background Colour
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}background-color
    value: "'rgb(0,0,0)'"
  become: true
  become_method: sudo

- name: Set Background Transparency Option
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}use-transparent-background
    value: "true"
  become: true
  become_method: sudo

- name: Set Transparencey Theme to false
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}use-theme-transparency
    value: "false"
  become: true
  become_method: sudo

- name: Define Background Transparency Value
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}background-transparency-percent
    value: "50"
  become: true
  become_method: sudo

- name: Disable Menu Bar
  community.general.dconf:
    key: /org/gnome/terminal/legacy/:headerbar
    value: "false"
  become: true
  become_method: sudo

- name: Set Scrollback to Value unlimited
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}scrollback-unlimited
    value: "true"
  become: true
  become_method: sudo

- name: Set Terminal Default Width
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}default-size-colums
    value: "300"
  become: true
  become_method: sudo

- name: Set Terminal Default Height
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}default-size-rows
    value: "80" 
  become: true
  become_method: sudo

- name: Set Terminal Encoding
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ profile_id }}encoding
    value: "'UTF-8'" 
  become: true
  become_method: sudo

# Define TMUX 
- name: Set custom-command
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/{{profile_id}}custom-command"
    value: "'tmux'"

- name: Set use-custom-command
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/{{profile_id}}use-custom-command"
    value: "true"

