---
# Test
- hosts: localhost
  tags: always
  become: true

  tasks:
  - name: install packages
    package:
      name: 
      - htop
      - tmux
      - vim-nox
      - dconf-cli
      - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/esa-iss.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: cccp0
    dconf:
      key: "/org/mate/desktop/background/picture-uri"
      value: "'file:///usr/share/background/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: cccp0
    dconf:
      key: "/org/mate/desktop/background/picture-options"
      value: "'zoom'"


# Tasks to complete before running roles
#- hosts: all
#  tags: always
#  become: true
#  pre_tasks:
#    - name: pre-run | update package cache (debian, etc.)
#      tags: always
#      apt: update_cache=yes
#      changed_when: False
#      when: ansible_distribution in [ "Debian", "Ubuntu" ]

# Run roles
#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base
