---
# Test
- hosts: localhost
  tags: always
  become: true

  tasks:
  - name: Install important or required system packages
    package:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties
        - python3-pip
        - virtualenv
        - python3-setuptools
    #state: latest
    #update_cache: true

  - name: Install additional packages
    package:
      name: 
      - htop
      - tmux
      - vim-nox
      - dconf-cli
      - python3-psutil

  - name: Add Docker GPG apt KEY
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
      update_cache: true

  - name: copy wallpaper file
    copy:
      src: files/esa-iss.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: mnv1c
    dconf:
      key: "/org/mate/desktop/background/picture-uri"
      value: "'file:///usr/share/background/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: mnv1c
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"


# Tasks to complete before running roles
#- hosts: all
#  tags: always
#  become: true
#  pre_tasks:
#    - name: pre-run | update package cache (debian, etc.)
#      tags: always
#      apt: update_cache=yes
#      changed_when: False
#      when: ansible_distribution in [ "Debian", "Ubuntu" ]

# Run roles
#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base
