---
# Test
- hosts: localhost
  tags: always
  become: true

  tasks:
  - name: install packages
    package:
      name: 
      - htop
      - tmux
      - vim-nox

# Tasks to complete before running roles
#- hosts: all
#  tags: always
#  become: true
#  pre_tasks:
#    - name: pre-run | update package cache (debian, etc.)
#      tags: always
#      apt: update_cache=yes
#      changed_when: False
#      when: ansible_distribution in [ "Debian", "Ubuntu" ]

# Run roles
#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base
