---
# Test
- hosts: localhost
  tags: always
  become: true
  vars:
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
  - name: Update and upgrade all packages to the latest version
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600

  - name: Install important or required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - python3-pip
        - virtualenv
        - python3-setuptools
        - gnupg

  - name: Install additional packages
    package:
      name: 
      - htop
      - tmux
      - vim-nox
      - dconf-cli
      - python3-psutil

  - name: Create directory for Docker's GPG key
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add Docker GPG apt KEY
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/keyrings/docker.gpg
      state: present

  - name: Print architecture variables
    debug:
      msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

  - name: Add Docker Repository
    apt_repository:
      repo: deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_lsb.codename) }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      filename: docker
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
      update_cache: true

  - name: Add Docker group
    group:
      name: docker
      state: present

  - name: Add user to Docker group
    user:
      name: "{{ ansible_user }}"

  - name: Enable and start Docker services
    systemd:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
      - docker.service
      - containerd.service

  - name: copy wallpaper file
    copy:
      src: files/esa-iss.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: mnv1c
    dconf:
      key: "/org/mate/desktop/background/picture-uri"
      value: "'file:///usr/share/background/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: mnv1c
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"


# Tasks to complete before running roles
#- hosts: all
#  tags: always
#  become: true
#  pre_tasks:
#    - name: pre-run | update package cache (debian, etc.)
#      tags: always
#      apt: update_cache=yes
#      changed_when: False
#      when: ansible_distribution in [ "Debian", "Ubuntu" ]

# Run roles
#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base
