- name: Whoami
  ansible.builtin.command: whoami
  become: yes
  become_user: mnv1c
  register: local_user

- name: Checkout NeoVim Base IDE
  ansible.builtin.git:
    repo: 'https://github.com/weinmann-phil/base-setup.nvim.git'
    dest: "/home/{{ local_user.stdout }}/.config/nvim"
    version: main

- name: Install Alire for Language Server Support
  ansible.builtin.git:
    repo: 'https://github.com/alire-project/alire.git'
    dest: "/home/{{ local_user.stdout }}/.config/alire"
    version: master
    # track_submodules: true
    force: yes

- name: Build Alire CLI
  ansible.builtin.script: "/home/{{ local_user.stdout }}/.config/alire/dev/build.sh"
  args:
    chdir: "/home/{{ local_user.stdout }}/.config/alire"

- name: CHeck if Alire Binaries Exist
  ansible.builtin.stat:
    path: "/home/{{ local_user.stdout }}/.config/alire/bin/alr"
  register: source_file_stat

- name: Move binaries to /usr/bin/
  ansible.builtin.copy:
    src: "/home/{{ local_user.stdout }}/.config/alire/bin/alr"
    dest: "/usr/bin"
  when: source_file_stat.exists

- name: Remove Binary Source File
  ansible.builtin.file:
    path: "/home/{{ local_user.stdout }}/.config/alire/bin/alr"
    state: absent
  when: source_file_stat.exists

    
