# Install packages by using NPM
- name: Whoami
  ansible.builtin.command: whoami
  become: yes
  become_user: mnv1c
  register: local_user

- name: Install NVim-Treesitter CLI with NPM
  community.general.npm:
    name: tree-sitter-cli
    global: yes
  become: yes
  become_user: "{{ local_user.stdout }}"
  environment:
    PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.npm-global/bin'
