# Install DotNet
- name: Create direcoty for Docker's GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add DotNet GPG key
  apt_repository:
    validate_certs: no
    repo: ppa:dotnet/backports
    state: present

- name: Update apt and Install DotNet
  apt:
    name: dotnet-sdk-9.0
    state: present
    update_cache: true

- name: Add dotnet group
  group:
    name: dotnet
    state: present

- name: Add user to dotnet group
  user:
    name: {{ host_username.stdout }} 
    

