# Install APT Packages
- name: Whoami
  ansible.builtin.command: whoami
  become: yes
  become_user: mnv1c
  register: local_user

- name: Install system and application packages with APT
  ansible.builtin.apt:
    pkg: 
      - apt-transport-https
      - bat
      - ca-certificates
      - curl
      - dconf-cli
      - default-jdk
      - default-jre
      - dnsutils
      - dotnet-runtime-8.0
      - dotnet-sdk-8.0
      #- fastfetch
      - gnat-13
      - gnupg
      - gpp
      - gprbuild
      - htop
      - openjdk-21-jdk
      - mysql-client
      - neovim
      - netcat-traditional
      - postgresql-client
      - python3-pip
      - python3-setuptools
      - software-properties-common
      - tree
      - virtualenv
      - zsh

