# Install packages with Ubuntu Snap
- name: Whoami
  ansible.builtin.command: whoami
  become: yes
  become_user: mnv1c
  register: local_user

- name: Install Classic Packages
  community.general.snap:
    name: "{{ item }}"
    classic: yes
  loop:
    - opentofu
    - go
    - aws-cli
    - google-cloud-cli
    - kubectl
    - kubelet
    - node

- name: Install Simple Packages
  community.general.snap:
    name: "{{ item }}"
    classic: no
  loop:
    - keepassxc
    - kompose
    - kube-apiserver
    - mqttx
    - multipass
    - nmap
    - postman
    - slack
    - terraform-docs
