# Create folders for development
- name: Create git directory
  ansible.builtin.file:
    path: /home/mnv1c/git/weinmann-phil
    state: directory
    mode: '0755'

# Create subfolders for ~/Documents
#- name: Create
