- name: Copy Wallpaper File
  copy:
    src: imgs/stars-wallpaper.png
    dest: /usr/share/backgrounds/stars-wallpaper.png
    owner: root
    group: root

- name: Set wallpaper
  become_user: mnv1c
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/stars-wallpaper.png'"

- name: Position Wallpaper
  become_user: mnv1c
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
