#SPDX-License-Identifier: MIT-0
---
# APT Packages file for roles/install_applications
- name: Install System and Application Packages with APT
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - bat
      - ca-certificates
      - conntrack
      - curl
      - dconf-cli
      - default-jdk
      - default-jre
      - dnsutils
      - dotnet-runtime-8.0
      - dotnet-sdk-8.0
      - gnat-13
      - gnupg
      - gpp
      - gprbuild
      - htop
      - openjdk-21-jdk
      - maven
      - mysql-client
      - neovim
      - netcat-traditional
      - postgresql-client
      - python3-pip
      - python3-setuptools
      - software-properties-common
      - tree
      - virtualenv
      - zsh

- name: Set ZSH as Main Terminal
  ansible.builtin.command: "chsh -s /usr/bin/zsh"
  delegate_to: localhost
  become: yes
  become_user: "{{ user }}"
  become_medhod: sudo

