#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/install_applications
- name: Install Classic Packages
  community.general.snap:
    name: "{{ item }}"
    classic: true
  loop:
    - opentofu
    - go
    - aws-cli
    - google-cloud-cli
    - kubectl
    - kubelet
    - node
    - ruby
  become: true
  become_method: sudo

- name: Install Simple Packages
  community.general.snap:
    name: "{{ item }}"
    classic: false
  loop:
    - keepassxc
    - kompose
    - kube-apiserver
    - mqttx
    - multipass
    - nmap
    - postman
    - slack
    - terraform-docs
  become: true
  become_method: sudo
