#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/install_applications
- name: Install Node Version Manager 
  ansible.builtin.shell: >
    curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    creates=/home/{{ user }}/.nvm/nvm.sh
  become: true
  become_method: sudo
